[versions]

# Plugins

#noinspection NewerVersionAvailable
composePlugin = "1.11.0-alpha01"

#noinspection NewerVersionAvailable
composeAndroid = "1.11.0-alpha02"

agp = "8.13.2"
kotlin = "2.3.0"

#noinspection NewerVersionAvailable
vanniktechMavenPublish = "0.34.0"

# Core Dependencies
core-ktx = "1.17.0"
lifecycle = "2.9.6"

# Compose Dependencies
activity-compose = "1.12.2"
navigation-compose = "2.9.1"

# Other
systemUiBarsTweaker = "1.3.0"
kotlinx-coroutines = "1.10.2"
koin = "4.1.1"

# =================================================================================================

[libraries]

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composePlugin" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composePlugin" }
lifecycle-runtime-ktx = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime", version.ref = "lifecycle" }
lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composePlugin" }
material3-windowsizeclass = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "composePlugin" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composePlugin" }
systemUiBarsTweaker = { group = "com.github.stoyan-vuchev", name = "system-ui-bars-tweaker", version.ref = "systemUiBarsTweaker" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composePlugin" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composePlugin" }
ui-util = { module = "org.jetbrains.compose.ui:ui-util", version.ref = "composePlugin" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "composeAndroid" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "composeAndroid" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeAndroid" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

# =================================================================================================

[plugins]

androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "composePlugin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }